#!/bin/bash
# See example files at /usr/share/doc/live-build/examples

# Exit on error
set -e

# See man lb config
lb config noauto \
	--mode debian \
	--distribution stretch \
	--architecture amd64 \
	--updates false \
	--backports false \
	--source false \
	--debian-installer false \
	--archive-areas "main contrib non-free" \
	--apt-indices false \
	--apt-recommends false \
	--memtest none \
	--bootappend-live "boot=live components splash username=root hostname=caliburn noautologin" \
	--iso-application "caliburn linux" \
	--iso-publisher "csebesta" \
	--iso-volume "caliburn"
	#--linux-flavours 686-pae \
	#--grub-splash FILE \
